fix: Use GetEVMCoinDenom() instead of accessing Params.EvmDenom
The EVM Params struct doesn't have an EvmDenom field. Instead,
use the global GetEVMCoinDenom() function to retrieve the EVM
denomination.

This fixes the compilation error:
  evmParamsResp.Params.EvmDenom undefined